In [5]:
import pandas as pd
import json
import numpy as np
from urllib import request 
import os

In [3]:
request.urlretrieve("https://raw.githubusercontent.com/songys/Chatbot_data/master/ChatbotData%20.csv", filename="ChatBotData.csv")

('ChatBotData.csv', <http.client.HTTPMessage at 0x7f89d4422990>)

In [6]:
os.chdir("/home/bmllab/bml_pjh/project/chatbot/data")
train_data = pd.read_csv('ChatBotData.csv')

In [8]:
res_data=pd.read_excel('A 음식점(15,726).xlsx')

In [21]:
res_data.iloc[:2,1]

'지금 배달되나요?'

In [80]:
train_data=train_data.iloc[:,0:2]

In [12]:
file_name=['A 음식점(15,726).xlsx','B 의류(15,826).xlsx','C 학원(4,773).xlsx','D 소매점(14,949).xlsx','D 소매점(14,949).xlsx','F 카페(7,859).xlsx','G 숙박업(7,113).xlsx','H 관광여가오락(4,949).xlsx','I 부동산(8,131).xlsx']

In [83]:
for i in range(len(file_name)):
    if i==0:
        data=pd.read_excel(file_name[i])
    else:
        data1=pd.read_excel(file_name[i])
        data=pd.concat((data,data1),axis=0)

In [84]:
data['idx']=np.arange(data.shape[0])

In [85]:
data.set_index('idx',inplace=True)
data

,SPEAKER,SENTENCE,DOMAINID,DOMAIN,CATEGORY,SPEAKERID,SENTENCEID,MAIN,SUB,QA,QACNCT,MQ,SQ,UA,SA,개체명,용어사전,지식베이스,Unnamed: 18
idx,,,,,,,,,,,,,,,,,,,
0,고객,지금 배달되나요?,A,음식점,배달음식점,1,1,배달가능문의,NaN,Q,NaN,지금 배달되나요?,NaN,NaN,NaN,"수고, 지금, 배달",NaN,NaN,NaN
1,점원,아 네 배달됩니다,A,음식점,배달음식점,0,2,배달가능문의,NaN,A,NaN,NaN,NaN,NaN,아 네 배달됩니다,배달,NaN,NaN,NaN
2,고객,짬뽕류는 어떤 게 있나요? 잘 나가는 짬뽕 있나요?,A,음식점,배달음식점,1,3,베스트메뉴문의추천요청,NaN,Q,NaN,짬뽕류는 어떤 게 있나요? 잘 나가는 짬뽕 있나요?,NaN,NaN,NaN,짬뽕,NaN,짬뽕/메뉴,NaN
3,점원,특해물 짬뽕도 있고 전복 새우 짬뽕도 있고 해물 종류도 새우 홍합 전복 없는 게 없습니다,A,음식점,배달음식점,0,4,베스트메뉴문의추천요청,NaN,A,NaN,NaN,NaN,NaN,특해물 짬뽕도 있고 전복 새우 짬뽕도 있고 해물 종류도 새우 홍합 전복 없는 게 없습니다,"특해물 짬뽕, 전복 새우 짬뽕, 해물 종류, 새우, 홍합, 전복",NaN,"특해물 짬뽕/메뉴, 전복 새우 짬뽕/메뉴, 새우/해물/재료, 홍합/해물/재료, 전복...",NaN
4,고객,전복 들어가는 거는 특해물 짬뽕 시켜야 돼요?,A,음식점,배달음식점,1,5,메뉴정보문의,NaN,Q,NaN,전복 들어가는 거는 특해물 짬뽕 시켜야 돼요?,NaN,NaN,NaN,"전복, 특해물 짬뽕",NaN,"전복/해물/재료, 특해물 짬뽕/메뉴",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94270,고객,1억 원대에 매매 가능한 토지 있어요?,I,부동산업,토지,1,1459,희망매매가매물문의,NaN,Q,NaN,1억 원대에 매매 가능한 토지 있어요?,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94271,고객,평당 500만 원 정도로 매매 가능한 토지 있는지 알려주실래요?,I,부동산업,토지,1,1460,희망매매가매물문의,NaN,Q,NaN,평당 500만 원 정도로 매매 가능한 토지 있는지 알려주실래요?,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94272,고객,2억 5000만 원까지 생각하고 있는데 그런 토지가 있나요?,I,부동산업,토지,1,1461,희망매매가매물문의,NaN,Q,NaN,2억 5000만 원까지 생각하고 있는데 그런 토지가 있나요?,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94273,고객,지금 가장 싼 토지 매물 한 번 보여주실래요?,I,부동산업,토지,1,1462,희망매매가매물문의,NaN,Q,NaN,지금 가장 싼 토지 매물 한 번 보여주실래요?,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94274,고객,평당 90만으로 괜찮은 곳 있어요?,I,부동산업,토지,1,1463,희망매매가매물문의,NaN,Q,NaN,평당 90만으로 괜찮은 곳 있어요?,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:

for i in range(data.shape[0]-2):
    if i%2==0 :
        if i==0:
            data__=pd.DataFrame({"Q":[data.iloc[i:i+2,1][0]],"A":[data.iloc[i:i+2,1][1]]})
        else:
       
            q=data.iloc[i:i+2,1][i]
            l=data.iloc[i:i+2,1][i+1]
            data__.loc[i]=[q,l]
    else:
        continue

In [87]:
real_data=pd.concat((train_data,data__),axis=0)

In [88]:
real_data

                                       Q                                    A
0                                 12시 땡!                           하루가 또 가네요.
1                            1지망 학교 떨어졌어                            위로해 드립니다.
2                           3박4일 놀러가고 싶다                          여행은 언제나 좋죠.
3                        3박4일 정도 놀러가고 싶다                          여행은 언제나 좋죠.
4                                PPL 심하네                           눈살이 찌푸려지죠.
...                                  ...                                  ...
94264                지하까지 해서 총 몇 층 가능해요?                     정확히 몇 층까지 가능한데요?
94266          그 토지 건물 올리는 거 몇 층까지 가능해요?           2억 원대에서 살 수 있는 토지 매물이 있나요?
94268            평당 천만 원 이하인 토지 매물 있을까요?                    가장 비싼 토지 매물이 뭔가요?
94270              1억 원대에 매매 가능한 토지 있어요?  평당 500만 원 정도로 매매 가능한 토지 있는지 알려주실래요?
94272  2억 5000만 원까지 생각하고 있는데 그런 토지가 있나요?            지금 가장 싼 토지 매물 한 번 보여주실래요?

[58960 rows x 2 columns]

In [89]:
real_data.to_csv("chatbot_data.csv")